export const ChallengeTypes = {
    GET_CHALLENGE: 'GET_CHALLENGE',
    REGISTER_CHALLENGE: 'REGISTER_CHALLENGE',
    UPATE_CHALLENGE: 'UPATE_CHALLENGE',
    DELETE_CHALLENGE: 'DELETE_CHALLENGE',
    SUCCESS: 'SUCCESS',
    FAIL: 'FAIL'
}