import { Input, Form, Avatar, Card, Menu, Icon, Row, Col, Tag, Tooltip, Divider, Button, Timeline, PageHeader, Collapse, Table, Popconfirm, Upload, Modal, message } from 'antd';
import Paragraph from 'antd/lib/typography/Paragraph';
import 'antd/dist/antd.css';

export const InputComp = Input;
export const FormComp = Form;
export const AvatarComp = Avatar;
export const IconComp = Icon;
export const CardComp = Card;
export const MenuComp = Menu;
export const ColComp = Col;
export const RowComp = Row;
export const TagComp = Tag;
export const TableComp = Table;
export const TooltipComp = Tooltip;
export const DividerComp = Divider;
export const PopConfirmComp = Popconfirm;
export const ButtonComp = Button;
export const PageHeaderComp = PageHeader;
export const ParagraphComp = Paragraph;
export const TimeLineComp = Timeline;
export const CollapseComp = Collapse;
export const PopconfirmComp = Popconfirm;
export const UploadComp = Upload;
export const ModalComp = Modal;
export const MessageComp = message;