export const ContextTypes = {
    GET_CONTEXT: 'GET_CONTEXT',
    REGISTER_CONTEXT: 'REGISTER_CONTEXT',
    UPATE_CONTEXT: 'UPATE_CONTEXT',
    DELETE_CONTEXT: 'DELETE_CONTEXT',
    SUCCESS: 'SUCCESS',
    FAIL: 'FAIL'
}